# Site settings
title: Moorabbin Kangaroos Football Club
email: media@mkfc.org.au
description: Official site of the Moorabbin Kangaroos FC
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.mkfc.org.au" # the base hostname & protocol for your site, e.g. http://example.com

avatar: "/favicon.png"

# Your name to show in the footer
author: Moorabbin Kangaroos

# Build settings
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-github-metadata

header_pages:
  - index.md
  - about/index.md
  - news/index.md
  - players/index.md
  - gallery/index.md
  - sponsors/index.md
  - calendar/index.md
  - contact/index.md

show_excerpts: true

defaults:
  - scope:
      path: ""
    values:
      image: /logo-2025.jpg

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - CHANGELOG.md
  - CNAME
  - LICENSE
  - README.md
  - screenshot.png
  - docs/
  - branding.md
  - CLAUDE.md
